channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- torchvision>=0.9.1
- pip
- pip:
  - mlflow
  - sklearn
  - transformers
  - torch>=1.9.0
  - torchtext>=0.10.0
  - pytorch-lightning>=1.3.5
