channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.8.1
- torchvision>=0.9.1
- pip
- pip:
  - mlflow
  - sklearn
  - transformers
  - torchtext>=0.9.1
  - pytorch-lightning>=1.3.5
